//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OxygenU.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("./scripts")]
        public string DefaultScriptDirectory {
            get {
                return ((string)(this["DefaultScriptDirectory"]));
            }
            set {
                this["DefaultScriptDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\"?>\r\n\r\n<!-- Please don\'t edit this if you\r\n      don\'t know wha" +
            "t you\'re doing.\r\n-->\r\n\r\n<SyntaxDefinition name=\"Lua\" extensions=\".lua\" xmlns=\"ht" +
            "tp://icsharpcode.net/sharpdevelop/syntaxdefinition/2008\">\r\n    <Color name=\"Comm" +
            "ent\" foreground=\"#FF57A64A\" exampleText=\"-- comment\" />\r\n    <Color name=\"String" +
            "\" foreground=\"#FFD69D85\" />\r\n    <Color name=\"Punctuation\" foreground=\"#FFDCDCDC" +
            "\" />\r\n    <Color name=\"MethodCall\" foreground=\"#FFDCDCAA\" />\r\n    <Color name=\"N" +
            "umberLiteral\" foreground=\"#FFB5CEA8\" />\r\n    <Color name=\"NilKeyword\" foreground" +
            "=\"#FF569CD6\" />\r\n    <Color name=\"Keywords\" foreground=\"#FF569CD6\" />\r\n    <Colo" +
            "r name=\"GotoKeywords\" foreground=\"#fcfcfc\" />\r\n    <Color name=\"Visibility\" fore" +
            "ground=\"#FF4EC9B0\" />\r\n    <Color name=\"TrueFalse\" foreground=\"#FF569CD6\" />\r\n  " +
            "  <Color name=\"LuaUKeywords\" foreground=\"#FF4EC9B0\" />\r\n\r\n    <RuleSet name=\"Com" +
            "mentMarkerSet\">\r\n        <Keywords fontWeight=\"bold\" foreground=\"#5e5e5e\">\r\n    " +
            "        <Word>TODO</Word>\r\n            <Word>FIXME</Word>\r\n        </Keywords>\r\n" +
            "        <Keywords fontWeight=\"bold\" foreground=\"#5e5e5e\">\r\n            <Word>HAC" +
            "K</Word>\r\n            <Word>UNDONE</Word>\r\n        </Keywords>\r\n    </RuleSet>\r\n" +
            "\r\n    <RuleSet>\r\n        <Span color=\"Comment\" ruleSet=\"CommentMarkerSet\" multil" +
            "ine=\"true\">\r\n            <Begin>--\\[[=]*\\[</Begin>\r\n            <End>\\][=]*]</En" +
            "d>\r\n        </Span>\r\n\r\n        <Span color=\"Comment\" ruleSet=\"CommentMarkerSet\">" +
            "\r\n            <Begin>--</Begin>\r\n        </Span>\r\n\r\n        <Span color=\"String\"" +
            ">\r\n            <Begin>\"</Begin>\r\n            <End>\"</End>\r\n            <RuleSet>" +
            "\r\n                <Span begin=\"\\\\\" end=\".\" />\r\n            </RuleSet>\r\n        <" +
            "/Span>\r\n\r\n        <Span color=\"String\">\r\n            <Begin>\'</Begin>\r\n         " +
            "   <End>\'</End>\r\n            <RuleSet>\r\n                <Span begin=\"\\\\\" end=\".\"" +
            " />\r\n            </RuleSet>\r\n        </Span>\r\n\r\n        <Span color=\"String\" mul" +
            "tiline=\"true\">\r\n            <Begin color=\"String\">\\[=*\\[</Begin>\r\n            <E" +
            "nd color=\"String\">\\]=*\\]</End>\r\n        </Span>\r\n\r\n        <Keywords color=\"True" +
            "False\">\r\n            <Word>true</Word>\r\n            <Word>false</Word>\r\n        " +
            "</Keywords>\r\n\r\n        <Keywords color=\"Keywords\">\r\n            <Word>and</Word>" +
            "\r\n            <Word>break</Word>\r\n            <Word>do</Word>\r\n            <Word" +
            ">else</Word>\r\n            <Word>elseif</Word>\r\n            <Word>end</Word>\r\n   " +
            "         <Word>false</Word>\r\n            <Word>for</Word>\r\n            <Word>fun" +
            "ction</Word>\r\n            <Word>if</Word>\r\n            <Word>in</Word>\r\n        " +
            "    <Word>local</Word>\r\n            <Word>not</Word>\r\n            <Word>or</Word" +
            ">\r\n            <Word>repeat</Word>\r\n            <Word>return</Word>\r\n           " +
            " <Word>then</Word>\r\n            <Word>true</Word>\r\n            <Word>until</Word" +
            ">\r\n            <Word>while</Word>\r\n\r\n            <!--Section 1-->\r\n        </Key" +
            "words>\r\n\r\n        <Keywords color=\"GotoKeywords\">\r\n            <Word>break</Word" +
            ">\r\n            <Word>return</Word>\r\n        </Keywords>\r\n\r\n        <Keywords col" +
            "or=\"Visibility\">\r\n            <Word>local</Word>\r\n            <Word>self</Word>\r" +
            "\n        </Keywords>\r\n\r\n        <Keywords color=\"NilKeyword\">\r\n            <Word" +
            ">nil</Word>\r\n        </Keywords>\r\n\r\n        <Keywords color=\"LuaUKeywords\">\r\n   " +
            "         <Word>assert</Word>\r\n            <Word>collectgarbage</Word>\r\n         " +
            "   <Word>dofile</Word>\r\n            <Word>error</Word>\r\n            <Word>_G</Wo" +
            "rd>\r\n            <Word>getmetatable</Word>\r\n            <Word>ipairs</Word>\r\n   " +
            "         <Word>loadfile</Word>\r\n            <Word>next</Word>\r\n            <Word" +
            ">pairs</Word>\r\n            <Word>pcall</Word>\r\n            <Word>print</Word>\r\n " +
            "           <Word>rawequal</Word>\r\n            <Word>rawget</Word>\r\n            <" +
            "Word>rawset</Word>\r\n            <Word>setmetatable</Word>\r\n            <Word>ton" +
            "umber</Word>\r\n            <Word>tostring</Word>\r\n            <Word>type</Word>\r\n" +
            "            <Word>_VERSION</Word>\r\n            <Word>xpcall</Word>\r\n            " +
            "<Word>string</Word>\r\n            <Word>table</Word>\r\n            <Word>math</Wor" +
            "d>\r\n            <Word>coroutine</Word>\r\n            <Word>io</Word>\r\n           " +
            " <Word>os</Word>\r\n            <Word>debug</Word>\r\n            <Word>getfenv</Wor" +
            "d>\r\n            <Word>gcinfo</Word>\r\n            <Word>load</Word>\r\n            " +
            "<Word>loadlib</Word>\r\n            <Word>loadstring</Word>\r\n            <Word>req" +
            "uire</Word>\r\n            <Word>select</Word>\r\n            <Word>setfenv</Word>\r\n" +
            "            <Word>unpack</Word>\r\n            <Word>_LOADED</Word>\r\n            <" +
            "Word>LUA_PATH</Word>\r\n            <Word>_REQUIREDNAME</Word>\r\n            <Word>" +
            "package</Word>\r\n            <Word>rawlen</Word>\r\n            <Word>package</Word" +
            ">\r\n            <Word>bit32</Word>\r\n            <Word>utf8</Word>\r\n            <W" +
            "ord>_ENV</Word>\r\n            <Word>Axes</Word>\r\n            <Word>CFrame</Word>\r" +
            "\n            <Word>CoordinateFrame</Word>\r\n            <Word>Content</Word>\r\n   " +
            "         <Word>DockWidgetPluginGuiInfo</Word>\r\n            <Word>Enum</Word>\r\n  " +
            "          <Word>Faces</Word>\r\n            <Word>NumberRange</Word>\r\n            " +
            "<Word>PathWaypoint</Word>\r\n            <Word>PhysicalProperties</Word>\r\n        " +
            "    <Word>Random</Word>\r\n            <Word>Ray</Word>\r\n            <Word>RbxLibr" +
            "ary</Word>\r\n            <Word>Rect</Word>\r\n            <Word>Region3</Word>\r\n   " +
            "         <Word>Region3int16</Word>\r\n            <Word>StamperController</Word>\r\n" +
            "            <Word>UDim</Word>\r\n            <Word>UDim2</Word>\r\n            <Word" +
            ">TweenInfo</Word>\r\n            <Word>BrickColor</Word>\r\n            <Word>Color3" +
            "</Word>\r\n            <Word>ColorSequence</Word>\r\n            <Word>ColorSequence" +
            "Keypoint</Word>\r\n            <Word>NumberSequence</Word>\r\n            <Word>Numb" +
            "erSequenceKeypoint</Word>\r\n            <Word>Vector2</Word>\r\n            <Word>V" +
            "ector3</Word>\r\n            <Word>Vector2int16</Word>\r\n            <Word>Vector3i" +
            "nt16</Word>\r\n            <Word>Instance</Word>\r\n\r\n        </Keywords>\r\n\r\n       " +
            " <Rule color=\"MethodCall\">\r\n      \\b\r\n      [\\d\\w_]+  # an identifier\r\n      (?=" +
            "\\s*\\() # followed by (\r\n    </Rule>\r\n        <Rule color=\"MethodCall\">\r\n      \\b" +
            "\r\n      [\\d\\w_]+  # an identifier\r\n      (?=\\s*\\\") # followed by \"\r\n    </Rule>\r" +
            "\n        <Rule color=\"MethodCall\">\r\n      \\b\r\n      [\\d\\w_]+  # an identifier\r\n " +
            "     (?=\\s*\\\') # followed by \'\r\n    </Rule>\r\n        <Rule color=\"MethodCall\">\r\n" +
            "      \\b\r\n      [\\d\\w_]+  # an identifier\r\n      (?=\\s*\\{) # followed by {\r\n    " +
            "</Rule>\r\n\r\n        <Rule color=\"NumberLiteral\">\r\n      \\b\r\n      0[xX][0-9a-fA-F" +
            "]+  # hex number\r\n      |\r\n      ( \\b\\d+(\\.[0-9]+)?   #number with optional floa" +
            "ting point\r\n      | \\.[0-9]+           #or just starting with floating point\r\n  " +
            "    )\r\n      ([eE][+-]?[0-9]+)?   # optional exponent\r\n    </Rule>\r\n\r\n        <R" +
            "ule color=\"Punctuation\">\r\n      [?,.;()\\[\\]{}+\\-/%*&lt;&gt;^+~!|&amp;#=]+\r\n    <" +
            "/Rule>\r\n    </RuleSet>\r\n</SyntaxDefinition>")]
        public string DefaultSyntax {
            get {
                return ((string)(this["DefaultSyntax"]));
            }
            set {
                this["DefaultSyntax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DefaultTopMost {
            get {
                return ((bool)(this["DefaultTopMost"]));
            }
            set {
                this["DefaultTopMost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DefaultFadeInOut {
            get {
                return ((bool)(this["DefaultFadeInOut"]));
            }
            set {
                this["DefaultFadeInOut"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DefaultAutoAttach {
            get {
                return ((bool)(this["DefaultAutoAttach"]));
            }
            set {
                this["DefaultAutoAttach"] = value;
            }
        }
    }
}
